# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotemodel',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.postmodel'),
            preserve_default=False,
        ),
    ]
