# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_upvotemodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotemodel',
            name='post',
        ),
    ]
